### ISSUE TITLE
progress bars in notebooks do not work with tqdm>=4.36.1

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#1433]
``` python
/srv/public/marscher/software/miniconda3/envs/pyemma_tut/lib/python3.7/site-packages/pyemma/_base/progress/reporter/__init__.py in _progress_register(self, amount_of_work, description, stage, tqdm_args)
    143             if _attached_to_ipy_notebook_with_widgets():
    144                 from .notebook import my_tqdm_notebook
--> 145                 pg = my_tqdm_notebook(leave=False, **args)
    146             else:
    147                 import tqdm

/srv/public/marscher/software/miniconda3/envs/pyemma_tut/lib/python3.7/site-packages/tqdm/notebook.py in __init__(self, *args, **kwargs)
    216         # Print initial bar state
    217         if not self.disable:
--> 218             self.display()
    219 
    220     def __iter__(self, *args, **kwargs):

/srv/public/marscher/software/miniconda3/envs/pyemma_tut/lib/python3.7/site-packages/tqdm/notebook.py in display(self, msg, pos, close, bar_style)
    151             msg = self.__repr__()
    152 
--> 153         pbar, ptext = self.container.children
    154         pbar.value = self.n
    155 

AttributeError: 'function' object has no attribute 'children'
```
