### ISSUE TITLE
pyemma.coordinates.source unable to accept a list with length more than 2

### ISSUE THREAD

**Issue by lucl13** [markovmodel/PyEMMA#1465]
Hi all,

inp = coor.source(traj_list, feat) doesn't work properly. If works fine in my old computer and it raises the error if the length of traj_list is more than 2.

********************
Obtaining file info
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-60-7cac76abcdf0> in <module>
----> 1 inp = coor.source(traj_list[0:3], feat)
      2 inp.dimension()

~/opt/anaconda3/envs/pyemma254/lib/python3.6/site-packages/pyemma/coordinates/api.py in source(inp, features, top, chunksize, **kw)
    384             isinstance(inp, (list, tuple))
    385             and (any(isinstance(item, (list, tuple, _string_types)) for item in inp) or len(inp) is 0)):
--> 386         reader = create_file_reader(inp, top, features, chunksize=cs, **kw)
    387 
    388     elif isinstance(inp, _np.ndarray) or (isinstance(inp, (list, tuple))

~/opt/anaconda3/envs/pyemma254/lib/python3.6/site-packages/pyemma/coordinates/data/util/reader_utils.py in create_file_reader(input_files, topology, featurizer, chunksize, **kw)
    111 
    112                     reader = FeatureReader(input_list, featurizer=featurizer, topologyfile=topology,
--> 113                                            chunksize=chunksize)
    114                 else:
    115                     if suffix in ['.npy', '.npz']:

~/opt/anaconda3/envs/pyemma254/lib/python3.6/site-packages/pyemma/coordinates/data/feature_reader.py in __init__(self, trajectories, topologyfile, chunksize, featurizer)
     93         self._is_reader = True
     94         self.topfile = topologyfile
---> 95         self.filenames = trajectories
     96         self._return_traj_obj = False
     97 

~/opt/anaconda3/envs/pyemma254/lib/python3.6/site-packages/pyemma/coordinates/data/_base/datasource.py in filenames(self, filename_list)
    117             from pyemma._base.progress import ProgressReporter
    118             pg = ProgressReporter()
--> 119             pg.register(len(filename_list), 'Obtaining file info')
    120             with pg.context():
    121                 for filename in filename_list:

~/opt/anaconda3/envs/pyemma254/lib/python3.6/site-packages/pyemma/_base/progress/reporter/__init__.py in register(self, amount_of_work, description, stage, tqdm_args)
    218 
    219     def register(self, amount_of_work, description='', stage=0, tqdm_args=None):
--> 220         self._progress_register(amount_of_work=amount_of_work, description=description, stage=stage, tqdm_args=tqdm_args)
    221 
    222     def update(self, increment, stage=0):

~/opt/anaconda3/envs/pyemma254/lib/python3.6/site-packages/pyemma/_base/progress/reporter/__init__.py in _progress_register(self, amount_of_work, description, stage, tqdm_args)
    143             if _attached_to_ipy_notebook_with_widgets():
    144                 from .notebook import my_tqdm_notebook
--> 145                 pg = my_tqdm_notebook(leave=False, **args)
    146             else:
    147                 import tqdm

~/opt/anaconda3/envs/pyemma254/lib/python3.6/site-packages/tqdm/notebook.py in __init__(self, *args, **kwargs)
    211         # Print initial bar state
    212         if not self.disable:
--> 213             self.display()
    214 
    215     def __iter__(self, *args, **kwargs):

~/opt/anaconda3/envs/pyemma254/lib/python3.6/site-packages/tqdm/notebook.py in display(self, msg, pos, close, bar_style)
    143             msg = self.__repr__()
    144 
--> 145         pbar, ptext = self.container.children
    146         pbar.value = self.n
    147 

AttributeError: 'function' object has no attribute 'children'
********************

- [ 2.5.4 and 2.5.6 same error, macOS catalina 10.15.5] PyEMMA version and operating system versions
- python 3.7 same error, so I created  python 3.6.5 env as in my old computer 

Could anybody offer some advice?
Thanks in advance.

Best,
Chenlin
[conda_list.txt](https://github.com/markovmodel/PyEMMA/files/4889923/conda_list.txt)

**Comment by clonker** [comment]
This seems to be a duplicate of #1433. Your PyEMMA version is not up to date, can you update to `2.5.7` and try again?

**Comment by lucl13** [comment]
> This seems to be a duplicate of #1433. Your PyEMMA version is not up to date, can you update to `2.5.7` and try again?

YES. It works fine in 2.5.7. Thanks. By the way, the error also appears in 2.5.6 (I have checked this morning).

**Comment by clonker** [comment]
Cool! Yeah the fix for that particular issue is rather recent. Glad it resolved itself for you, otherwise feel free to re-open (or open a new issue).
